-- Create subscriptions table if not exists
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  currency TEXT DEFAULT 'TWD',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  cycle TEXT NOT NULL CHECK (cycle IN ('30days', '6months', '1year')),
  icon_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add user_id column if it doesn't exist and set up RLS
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'subscriptions' AND column_name = 'user_id') THEN
    ALTER TABLE public.subscriptions ADD COLUMN user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
    UPDATE public.subscriptions SET user_id = auth.uid() WHERE user_id IS NULL;
    ALTER TABLE public.subscriptions ALTER COLUMN user_id SET NOT NULL;
  END IF;
END $$;

-- Enable Row Level Security (RLS) if not already enabled
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relname = 'subscriptions' AND n.nspname = 'public' AND c.relrowsecurity = true) THEN
    ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;

-- Create a policy that allows users to access only their own subscriptions if not exists
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'subscriptions' AND policyname = 'Users can access only their own subscriptions') THEN
    CREATE POLICY "Users can access only their own subscriptions" ON public.subscriptions
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;

-- Insert sample data if table is empty (Note: This will only work if there are authenticated users)
-- For development, you might want to insert data programmatically after user authentication